package com.msnguard.vpn

/**
 * Hand-curated UI strings: English, Persian, Chinese.
 * Key is usually the English text; a few keys carry a suffix (e.g. "Light — theme")
 * where one English word means two things, so each context can translate freely.
 * Persian per Mohsen's approved mapping; Chinese per his Simplified-Chinese map.
 * 2026-09-11.
 */
object Strings {


    private val table = mapOf(
        " (%s of %s)" to Triple(" (%s of %s)", " (%s از %s)", " (第 %s 个, 共 %s 个)"),
        "%s %s" to Triple("%s %s", "%s %s", "%s 个"),
        "%s %s — may fall back to another country" to Triple("%s %s — may fall back to another country", "%s %s — ممکن است به کشور دیگری منتقل شود", "%s 个出口节点 — 可能降级至其他国家"),
        "%s OVER WARP" to Triple("%s OVER WARP", "%s روی وارپ", "%s over WARP"),
        "%s bridges" to Triple("%s bridges", "%s پل", "%s 个桥"),
        "%s exit relay" to Triple("%s exit relay", "%s رله خروجی", "%s 个出口节点"),
        "%s exit relays" to Triple("%s exit relays", "%s رله خروجی", "%s 个出口节点"),
        "%s nodes available" to Triple("%s nodes available", "%s نود در دسترس", "%s 个节点可用"),
        "%s over WARP is active" to Triple("%s over WARP is active", "%s روی وارپ فعال است", "%s over WARP 已运行"),
        "%s over WARP recovered" to Triple("%s over WARP recovered", "%s روی وارپ بازیابی شد", "%s over WARP 已恢复"),
        "%s selected apps" to Triple("%s selected apps", "%s برنامه انتخاب‌شده", "%s 个应用已选"),
        "%s servers in the bundled list" to Triple("%s servers in the bundled list", "%s سرور در لیست داخلی", "%s 个内置节点"),
        "%s settings" to Triple("%s settings", "%s تنظیم", "%s 项设置"),
        "%s tunnel is active" to Triple("%s tunnel is active", "تونل %s فعال است", "%s 隧道已运行"),
        "%s tunnel recovered" to Triple("%s tunnel recovered", "تونل %s بازیابی شد", "%s 隧道已恢复"),
        "%s · tunnelled" to Triple("%s · tunnelled", "%s · از تونل", "%s · 已走隧道"),
        "(%s of %s)" to Triple("(%s of %s)", "(%s از %s)", "(%s / %s)"),
        "1 bridge" to Triple("1 bridge", "۱ پل", "1 个桥"),
        "1 selected app" to Triple("1 selected app", "۱ برنامه انتخاب‌شده", "1 个应用已选"),
        "1 server in the bundled list" to Triple("1 server in the bundled list", "۱ سرور در لیست داخلی", "1 个内置节点"),
        "ABOUT" to Triple("ABOUT", "درباره برنامه", "关于"),
        "ANTI-DPI" to Triple("ANTI-DPI", "ضد DPI", "抗 DPI"),
        "APPEARANCE" to Triple("APPEARANCE", "ظاهر برنامه", "外观"),
        "ARMED" to Triple("ARMED", "آماده‌به‌کار", "已就绪"),
        "Adjust traffic-shape padding for filtered networks" to Triple("Adjust traffic-shape padding for filtered networks", "تنظیم پدینگ شکل‌دهی ترافیک برای شبکه‌های دارای فیلترینگ", "调整数据包填充以对抗网络审查"),
        "Advanced obfuscation" to Triple("Advanced obfuscation", "مخفی‌سازی پیشرفته", "高级混淆设置"),
        "Aggressive" to Triple("Aggressive", "شدید", "强力"),
        "All" to Triple("All", "همه", "全部"),
        "All apps" to Triple("All apps", "همه برنامه‌ها", "所有应用"),
        "All apps use MSN-GUARD" to Triple("All apps use MSN-GUARD", "همه برنامه‌ها از MSN-GUARD استفاده می‌کنند", "所有应用均使用 MSN-GUARD"),
        "Anti-censorship tunnel" to Triple("Anti-censorship tunnel", "تونل ضد سانسور", "赛风抗封锁隧道"),
        "App" to Triple("App", "برنامه", "应用"),
        "App log cleared" to Triple("App log cleared", "گزارش برنامه پاک شد", "应用日志已清除"),
        "Applied on your next connection" to Triple("Applied on your next connection", "در اتصال بعدی‌ات اعمال می‌شود", "将在下次连接时生效"),
        "Applies straight away. A running tunnel is not interrupted." to Triple("Applies straight away. A running tunnel is not interrupted.", "بلافاصله اعمال می‌شود. تونل در حال اجرا قطع نخواهد شد.", "立即生效，不会中断当前正在运行的隧道。"),
        "Apply" to Triple("Apply", "اعمال", "应用"),
        "Apps" to Triple("Apps", "برنامه‌ها", "应用"),
        "Argentina" to Triple("Argentina", "آرژانتین", "阿根廷"),
        "Australia" to Triple("Australia", "استرالیا", "澳大利亚"),
        "Austria" to Triple("Austria", "اتریش", "奥地利"),
        "Auto" to Triple("Auto", "خودکار", "自动"),
        "Auto Scan" to Triple("Auto Scan", "اسکن خودکار", "自动扫描"),
        "Auto reconnect" to Triple("Auto reconnect", "اتصال مجدد خودکار", "自动重连"),
        "Automatic" to Triple("Automatic", "خودکار", "自动选择"),
        "BACKUP" to Triple("BACKUP", "پشتیبان‌گیری", "备份"),
        "Back up settings" to Triple("Back up settings", "پشتیبان‌گیری از تنظیمات", "备份设置"),
        "Balanced" to Triple("Balanced", "متعادل", "均衡"),
        "Belgium" to Triple("Belgium", "بلژیک", "比利时"),
        "Block all traffic if the tunnel drops" to Triple("Block all traffic if the tunnel drops", "قطع کامل اینترنت در صورت قطعی تونل", "隧道断开时阻断全部流量"),
        "Both" to Triple("Both", "هر دو (IPv4 و IPv6)", "双栈 (IPv4 + IPv6)"),
        "Brazil" to Triple("Brazil", "برزیل", "巴西"),
        "Bridge that hides Tor's traffic shape" to Triple("Bridge that hides Tor's traffic shape", "پلی که الگوی ترافیک تور را مخفی می‌کند", "混淆 Tor 流量特征的网桥"),
        "Bringing the tunnel down…" to Triple("Bringing the tunnel down…", "در حال قطع‌کردن تونل…", "正在断开隧道…"),
        "Bulgaria" to Triple("Bulgaria", "بلغارستان", "保加利亚"),
        "CHAINED" to Triple("CHAINED", "زنجیره‌ای", "链式"),
        "CONNECTING" to Triple("CONNECTING", "در حال اتصال...", "正在连接..."),
        "CONNECTING %s%%" to Triple("CONNECTING %s%%", "در حال اتصال %s%%", "正在连接 %s%%"),
        "CONNECTION" to Triple("CONNECTION", "تنظیمات اتصال", "连接"),
        "CONNECTION SHAPING" to Triple("CONNECTION SHAPING", "شکل‌دهی اتصال", "连接塑形"),
        "COPY" to Triple("COPY", "کپی", "复制"),
        "CURRENT" to Triple("CURRENT", "فعلی", "当前"),
        "Cache & refresh" to Triple("Cache & refresh", "کش و به‌روزرسانی", "缓存与刷新"),
        "Canada" to Triple("Canada", "کانادا", "加拿大"),
        "Cancel" to Triple("Cancel", "انصراف", "取消"),
        "Check for updates" to Triple("Check for updates", "بررسی به‌روزرسانی", "检查更新"),
        "Check the server and try again" to Triple("Check the server and try again", "سرور را بررسی کنید و دوباره امتحان کنید", "请检查服务器后重试"),
        "Checking for updates" to Triple("Checking for updates", "در حال بررسی بروزرسانی", "正在检查更新"),
        "Checking that traffic really passes" to Triple("Checking that traffic really passes", "بررسی برقراری واقعی ترافیک", "正在验证流量连通性"),
        "Chile" to Triple("Chile", "شیلی", "智利"),
        "Choose Aether's endpoint-discovery budget and address families" to Triple("Choose Aether's endpoint-discovery budget and address families", "تنظیم بودجه کشف نقطه پایانی Aether و خانواده‌های آدرس", "配置 Aether 节点探测策略与 IP 地址协议栈"),
        "Choose TLS curve ordering for QUIC connections" to Triple("Choose TLS curve ordering for QUIC connections", "انتخاب ترتیب منحنی‌های TLS برای اتصالات QUIC", "选择 QUIC 连接的 TLS 密码曲线顺序"),
        "Choose how MSN-GUARD connects" to Triple("Choose how MSN-GUARD connects", "نحوه اتصال MSN-GUARD را انتخاب کنید", "选择 MSN-GUARD 的连接协议"),
        "Choose which apps use MSN-GUARD. Changes apply next connection." to Triple("Choose which apps use MSN-GUARD. Changes apply next connection.", "برنامه‌هایی که از MSN-GUARD استفاده می‌کنند را انتخاب کنید. تغییرات در اتصال بعدی اعمال می‌شوند.", "选择使用 MSN-GUARD 的应用。设置将在下次连接时生效。"),
        "Chrome" to Triple("Chrome", "کروم (Chrome)", "Chrome 浏览器"),
        "Chrome TLS curve ordering" to Triple("Chrome TLS curve ordering", "ترتیب منحنی TLS استاندارد کروم", "标准 Chrome TLS 曲线顺序"),
        "Clear" to Triple("Clear", "پاک‌سازی", "清除"),
        "Clear saved gateways" to Triple("Clear saved gateways", "پاک‌سازی درگاه‌های ذخیره‌شده", "清除网关缓存"),
        "Compatibility" to Triple("Compatibility", "سازگاری کامل", "兼容模式"),
        "Connected" to Triple("Connected", "متصل شد", "已连接"),
        "Connecting" to Triple("Connecting", "در حال اتصال...", "正在连接..."),
        "Connecting %s through WARP…" to Triple("Connecting %s through WARP…", "اتصال %s از طریق وارپ…", "正在通过 WARP 连接 %s…"),
        "Connecting %s…" to Triple("Connecting %s…", "در حال اتصال %s…", "正在连接 %s…"),
        "Connecting Psiphon through %s…" to Triple("Connecting Psiphon through %s…", "اتصال سایفون از طریق %s…", "正在通过 %s 连接赛风…"),
        "Connecting Psiphon through \\\$outer…" to Triple("Connecting Psiphon through \\\$outer…", "اتصال سایفون از طریق \\\$outer…", "正在通过 \\\$outer 连接赛风…"),
        "Connecting \\\$inner through WARP…" to Triple("Connecting \\\$inner through WARP…", "اتصال \\\$inner از طریق وارپ…", "正在通过 WARP 连接 \\\$inner…"),
        "Connecting \\\$label…" to Triple("Connecting \\\$label…", "در حال اتصال \\\$label…", "正在连接 \\\$label…"),
        "Connecting…" to Triple("Connecting…", "در حال اتصال…", "正在连接…"),
        "Connection degraded" to Triple("Connection degraded", "اتصال ضعیف شده است", "连接质量下降"),
        "Connection failed" to Triple("Connection failed", "اتصال ناموفق بود", "连接失败"),
        "Connection mode" to Triple("Connection mode", "حالت اتصال", "连接模式"),
        "Control saved MASQUE gateway discovery data" to Triple("Control saved MASQUE gateway discovery data", "مدیریت داده‌های ذخیره‌شده شناسایی درگاه‌های MASQUE", "管理已保存的 MASQUE 网关探测数据"),
        "Core" to Triple("Core", "هسته", "核心"),
        "Could not connect on this carrier. Try Wi-Fi or another SIM." to Triple("Could not connect on this carrier. Try Wi-Fi or another SIM.", "روی این اپراتور وصل نشد. وای‌فای یا سیم کارت دیگر را امتحان کن.", "当前运营商无法连接。请尝试 Wi-Fi 或其他 SIM 卡。"),
        "Could not read the file: %s" to Triple("Could not read the file: %s", "خواندن فایل ممکن نشد: %s", "无法读取文件: %s"),
        "Could not read the file: \\\${it.message}" to Triple("Could not read the file: \\\${it.message}", "خواندن فایل ممکن نشد: \\\${it.message}", "无法读取文件：\\\${it.message}"),
        "Could not read the log: %s" to Triple("Could not read the log: %s", "خواندن گزارش ممکن نشد: %s", "无法读取日志: %s"),
        "Could not read the settings: %s" to Triple("Could not read the settings: %s", "خواندن تنظیمات ممکن نشد: %s", "无法读取设置: %s"),
        "Could not read the settings: \\\${it.message}" to Triple("Could not read the settings: \\\${it.message}", "خواندن تنظیمات ممکن نشد: \\\${it.message}", "无法读取设置：\\\${it.message}"),
        "Could not start whole-device routing" to Triple("Could not start whole-device routing", "مسیریابی کل دستگاه راه‌اندازی نشد", "无法启动整机路由"),
        "Could not update the list" to Triple("Could not update the list", "لیست بروزرسانی نشد", "无法更新列表"),
        "Could not write the backup: %s" to Triple("Could not write the backup: %s", "نوشتن فایل پشتیبان ممکن نشد: %s", "无法写入备份: %s"),
        "Could not write the backup: \\\${it.message}" to Triple("Could not write the backup: \\\${it.message}", "نوشتن پشتیبان ممکن نشد: \\\${it.message}", "无法写入备份：\\\${it.message}"),
        "Croatia" to Triple("Croatia", "کرواسی", "克罗地亚"),
        "Custom" to Triple("Custom", "سفارشی", "自定义"),
        "Custom Cloudflare IP applied: %s" to Triple("Custom Cloudflare IP applied: %s", "آی‌پی اختصاصی کلادفلر اعمال شد: %s", "自定义 Cloudflare IP 已应用: %s"),
        "Custom Cloudflare IP applied: \\\$ip" to Triple("Custom Cloudflare IP applied: \\\$ip", "IP سفارشی کلادفلر اعمال شد: \\\$ip", "已应用自定义 Cloudflare IP：\\\$ip"),
        "Custom IP cleared" to Triple("Custom IP cleared", "IP سفارشی پاک شد", "已清除自定义 IP"),
        "Czechia" to Triple("Czechia", "چک", "捷克"),
        "DESKTOP ONLY" to Triple("DESKTOP ONLY", "فقط دسکتاپ", "仅限桌面"),
        "DOWN" to Triple("DOWN", "دانلود", "下载"),
        "Dark" to Triple("Dark", "تاریک", "深色模式"),
        "Debug" to Triple("Debug", "عیب‌یابی (Debug)", "调试 (Debug)"),
        "Deep scan; selects best latency" to Triple("Deep scan; selects best latency", "اسکن عمیق؛ انتخاب بهترین تاخیر (Latency)", "全量深度扫描，优选最低延迟线路"),
        "Default mix of speed and coverage" to Triple("Default mix of speed and coverage", "ترکیب پیش‌فرض سرعت و پوشش", "速度与覆盖率的最佳平衡"),
        "Default verbosity" to Triple("Default verbosity", "سطح جزئیات پیش‌فرض", "默认日志级别"),
        "Denmark" to Triple("Denmark", "دانمارک", "丹麦"),
        "Desktop and powerful devices" to Triple("Desktop and powerful devices", "کامپیوترها و دستگاه‌های قدرتمند", "适用于桌面端及高配设备"),
        "Detect hardware and scale accordingly" to Triple("Detect hardware and scale accordingly", "شناسایی خودکار سخت‌افزار و تنظیم متناسب", "自动检测硬件并智能匹配"),
        "Direct" to Triple("Direct", "مستقیم", "直连"),
        "Direct, Meek and your own bridges, inside a WARP transport" to Triple("Direct, Meek and your own bridges, inside a WARP transport", "پل‌های مستقیم، Meek و اختصاصی در بستر وارپ", "直连、Meek 及自定义网桥，封装在 WARP 传输内"),
        "Disconnect" to Triple("Disconnect", "قطع اتصال", "断开连接"),
        "Disconnect first to change the port" to Triple("Disconnect first to change the port", "برای تغییر پورت اول قطعش کن", "更改端口前请先断开"),
        "Disconnect first to change the tunnel type" to Triple("Disconnect first to change the tunnel type", "برای تغییر نوع تانل اول قطعش کن", "更改隧道类型前请先断开"),
        "Disconnect first — a reset changes what the tunnel uses" to Triple("Disconnect first — a reset changes what the tunnel uses", "اول قطعش کن — ریست چیزهایی را عوض می‌کند که تانل استفاده می‌کند", "请先断开连接 — 重置会更改隧道所用的配置"),
        "Disconnect first — a restore changes what the tunnel uses" to Triple("Disconnect first — a restore changes what the tunnel uses", "اول قطعش کن — بازگردانی چیزهایی را عوض می‌کند که تانل استفاده می‌کند", "请先断开连接 — 恢复会更改隧道所用的配置"),
        "Disconnected" to Triple("Disconnected", "قطع شد", "已断开"),
        "Disconnecting" to Triple("Disconnecting", "در حال قطع اتصال", "正在断开"),
        "Done" to Triple("Done", "تایید", "完成"),
        "Double-layer tunnel" to Triple("Double-layer tunnel", "تونل دو لایه", "双层 WARP 加密隧道"),
        "Download" to Triple("Download", "دانلود", "下载"),
        "EXIT NODE" to Triple("EXIT NODE", "نود خروجی", "出口节点"),
        "English" to Triple("English", "انگلیسی", "英语"),
        "Enter Your Cloudflare IP" to Triple("Enter Your Cloudflare IP", "ورود آی‌پی کلادفلر", "自定义 Cloudflare IP"),
        "Enter a bridge first, in the row below this one" to Triple("Enter a bridge first, in the row below this one", "ابتدا در کادر زیرین یک پل وارد کنید", "请先在下方输入框中填入网桥地址"),
        "Enter a bridge in Manual bridge first" to Triple("Enter a bridge in Manual bridge first", "ابتدا در «پل دستی» یک پل وارد کنید", "请先在“手动桥”中输入一个桥"),
        "Error" to Triple("Error", "خطا (Error)", "错误 (Error)"),
        "Estonia" to Triple("Estonia", "استونی", "爱沙尼亚"),
        "Every app goes through the tunnel" to Triple("Every app goes through the tunnel", "تمام برنامه‌ها از تونل عبور می‌کنند", "所有应用均通过代理隧道传输"),
        "Exclude %s selected app" to Triple("Exclude %s selected app", "استثنا کردن %s برنامه انتخاب‌شده", "绕过 %s 个应用"),
        "Exclude %s selected app%s" to Triple("Exclude %s selected app%s", "استثنا کردن %s برنامه انتخاب‌شده%s", "绕过 %s 个应用%s"),
        "Exclude %s selected apps" to Triple("Exclude %s selected apps", "استثنا کردن %s برنامه انتخاب‌شده", "绕过 %s 个应用"),
        "Exclude 1 selected app" to Triple("Exclude 1 selected app", "استثنا کردن ۱ برنامه انتخاب‌شده", "绕过 1 个应用"),
        "Exclude selected apps" to Triple("Exclude selected apps", "استثنا کردن برنامه‌های انتخاب‌شده", "绕过选中应用"),
        "Fast" to Triple("Fast", "سریع", "快速"),
        "Fastest scan; first verified route wins" to Triple("Fastest scan; first verified route wins", "سریع‌ترین اسکن؛ انتخاب اولین مسیر تاییدشده", "最快速度扫描，优先选用首个通畅线路"),
        "Fastest — Psiphon picks whichever server answers first" to Triple("Fastest — Psiphon picks whichever server answers first", "سریع‌ترین — سایفون سروری را که زودتر پاسخ دهد انتخاب می‌کند", "极速 — 自动连接响应最快的服务器"),
        "Fastest — Tor picks from every exit relay" to Triple("Fastest — Tor picks from every exit relay", "سریع‌ترین — انتخاب از میان تمامی رله‌های خروجی تور", "极速 — 在所有出口中优选最佳节点"),
        "Finding a fast node…" to Triple("Finding a fast node…", "در حال یافتن گره سریع…", "正在寻找快速节点…"),
        "Finding the best MASQUE gateway" to Triple("Finding the best MASQUE gateway", "یافتن بهترین گره‌گاه MASQUE", "正在寻找最佳 MASQUE 网关"),
        "Finland" to Triple("Finland", "فنلاند", "芬兰"),
        "Follow system" to Triple("Follow system", "از سیستم پیروی کن", "跟随系统"),
        "Forget every setting" to Triple("Forget every setting", "پاکسازی تمام تنظیمات", "重置所有参数"),
        "Fragment TLS handshake to evade DPI" to Triple("Fragment TLS handshake to evade DPI", "تکه‌تکه‌کردن دست‌تکانی TLS جهت دور زدن فیلترینگ هوشمند (DPI)", "分片 TLS 握手包以对抗 DPI 深度包检测"),
        "Fragment the TLS ClientHello to look like ordinary HTTPS traffic" to Triple("Fragment the TLS ClientHello to look like ordinary HTTPS traffic", "تکه‌تکه‌کردن پکت ClientHello برای شبیه‌سازی ترافیک معمولی HTTPS", "对 TLS ClientHello 进行分片，伪装成普通 HTTPS 流量"),
        "France" to Triple("France", "فرانسه", "法国"),
        "Fresh scan" to Triple("Fresh scan", "اسکن جدید", "全新扫描"),
        "Fresh scan next time" to Triple("Fresh scan next time", "اسکن جدید در اتصال بعدی", "下次全新扫描"),
        "From a backup file" to Triple("From a backup file", "از فایل پشتیبان", "从备份文件导入"),
        "Full per-packet detail" to Triple("Full per-packet detail", "جزئیات کامل تمام پکت‌ها", "记录所有数据包的完整细节"),
        "Gateway cache" to Triple("Gateway cache", "کش درگاه‌ها", "网关缓存"),
        "Germany" to Triple("Germany", "آلمان", "德国"),
        "Greece" to Triple("Greece", "یونان", "希腊"),
        "HTTP/2" to Triple("HTTP/2", "HTTP/2", "HTTP/2"),
        "HTTP/3" to Triple("HTTP/3", "HTTP/3", "HTTP/3"),
        "HTTP/3 tunnel" to Triple("HTTP/3 tunnel", "تونل HTTP/3", "HTTP/3 隧道"),
        "HTTP/3, falling back to HTTP/2 with TLS fragmentation" to Triple("HTTP/3, falling back to HTTP/2 with TLS fragmentation", "پروتکل HTTP/3، با قابلیت بازگشت به HTTP/2 همراه با تکه‌تکه‌سازی TLS", "HTTP/3 协议，必要时降级至带 TLS 分片的 HTTP/2"),
        "High" to Triple("High", "بالا", "高性能"),
        "Highest resistance; slower setup" to Triple("Highest resistance; slower setup", "بیشترین مقاومت؛ اتصال اولیه کندتر", "最强抗封锁，建连时间略长"),
        "Hong Kong" to Triple("Hong Kong", "هنگ‌کنگ", "香港"),
        "How MSN-GUARD carries your traffic" to Triple("How MSN-GUARD carries your traffic", "نحوه انتقال ترافیک توسط MSN-GUARD", "MSN-GUARD 传输流量的方式"),
        "How Tor reaches the network. Auto tries each method until one works." to Triple("How Tor reaches the network. Auto tries each method until one works.", "نحوه ارتباط تور با شبکه. حالت خودکار روش‌ها را تا زمان برقراری اتصال امتحان می‌کند.", "Tor 接入网络的方式。“自动”模式将依次尝试直到成功建立连接。"),
        "How much the core logs · applies next connection" to Triple("How much the core logs · applies next connection", "میزان ثبت گزارش‌های هسته · در اتصال بعدی اعمال می‌شود", "控制核心日志输出级别（下次连接生效）"),
        "Hungary" to Triple("Hungary", "مجارستان", "匈牙利"),
        "INIT PACKET I1" to Triple("INIT PACKET I1", "پکت اولیه I1", "初始包 I1"),
        "INIT PACKET I2" to Triple("INIT PACKET I2", "پکت اولیه I2", "初始包 I2"),
        "IP VERSION" to Triple("IP VERSION", "نسخه IP", "IP 协议版本"),
        "IP unavailable" to Triple("IP unavailable", "آی‌پی در دسترس نیست", "IP 不可用"),
        "IP:port, blank for automatic" to Triple("IP:port, blank for automatic", "آی‌پی:پورت، برای حالت خودکار خالی بگذارید", "IP:端口，留空表示自动获取"),
        "IPv4" to Triple("IPv4", "فقط IPv4", "仅 IPv4"),
        "IPv6" to Triple("IPv6", "فقط IPv6", "仅 IPv6"),
        "Iceland" to Triple("Iceland", "ایسلند", "冰岛"),
        "Ignore saved gateways once" to Triple("Ignore saved gateways once", "نادیده‌گرفتن درگاه‌های ذخیره‌شده برای یک‌بار", "单次忽略已保存的网关"),
        "India" to Triple("India", "هند", "印度"),
        "Indonesia" to Triple("Indonesia", "اندونزی", "印度尼西亚"),
        "Info" to Triple("Info", "اطلاعات عمومی (Info)", "信息 (Info)"),
        "Install a browser, then download the update from GitHub." to Triple("Install a browser, then download the update from GitHub.", "یک مرورگر نصب کنید، سپس بروزرسانی را از گیت‌هاب دانلود کنید.", "请先安装浏览器，再从 GitHub 下载更新。"),
        "Invalid IP address" to Triple("Invalid IP address", "آدرس IP نامعتبر است", "无效的 IP 地址"),
        "Invalid IP format (use IPv4)" to Triple("Invalid IP format (use IPv4)", "قالب IP نامعتبر است (IPv4 بزن)", "IP 格式无效（请使用 IPv4）"),
        "Ireland" to Triple("Ireland", "ایرلند", "爱尔兰"),
        "Ironclad" to Triple("Ironclad", "سخت‌گیرانه (Ironclad)", "高可靠模式"),
        "Israel" to Triple("Israel", "اسرائیل", "以色列"),
        "Italy" to Triple("Italy", "ایتالیا", "意大利"),
        "JUNK COUNT (JC)" to Triple("JUNK COUNT (JC)", "تعداد پکت زاید (JC)", "垃圾包数量 (JC)"),
        "JUNK MAX (JMAX)" to Triple("JUNK MAX (JMAX)", "حداکثر حجم پکت زاید (JMAX)", "垃圾包最大长度 (JMAX)"),
        "JUNK MIN (JMIN)" to Triple("JUNK MIN (JMIN)", "حداقل حجم پکت زاید (JMIN)", "垃圾包最小长度 (JMIN)"),
        "Japan" to Triple("Japan", "ژاپن", "日本"),
        "Jc must be 0–10" to Triple("Jc must be 0–10", "Jc باید بین ۰ تا ۱۰ باشد", "Jc 取值 0–10"),
        "Jmax must be 0–1024" to Triple("Jmax must be 0–1024", "Jmax باید بین ۰ تا ۱۰۲۴ باشد", "Jmax 取值 0–1024"),
        "Jmax must be at least Jmin" to Triple("Jmax must be at least Jmin", "Jmax باید حداقل برابر Jmin باشد", "Jmax 不得小于 Jmin"),
        "Jmin must be 0–1024" to Triple("Jmin must be 0–1024", "Jmin باید بین ۰ تا ۱۰۲۴ باشد", "Jmin 取值 0–1024"),
        "Kill switch" to Triple("Kill switch", "قطع اضطراری (Kill Switch)", "断流保护 (Kill Switch)"),
        "Kill switch active — \\\$detail" to Triple("Kill switch active — \\\$detail", "کلید‌کشو فعال است — \\\$detail", "断流保护已启用 — \\\$detail"),
        "Kill switch active — tunnel dropped" to Triple("Kill switch active — tunnel dropped", "کلید‌کشو فعال است — تانل قطع شد", "断流保护已启用 — 隧道已断开"),
        "LAN sharing disabled — applies on the next connect" to Triple("LAN sharing disabled — applies on the next connect", "اشتراک LAN غیرفعال شد — در اتصال بعدی اعمال می‌شود", "局域网共享已停用 — 下次连接时生效"),
        "LAN sharing enabled — applies on the next connect" to Triple("LAN sharing enabled — applies on the next connect", "اشتراک LAN فعال شد — در اتصال بعدی اعمال می‌شود", "局域网共享已启用 — 下次连接时生效"),
        "LIVE SPEED" to Triple("LIVE SPEED", "سرعت لحظه‌ای", "实时网速"),
        "Language" to Triple("Language", "زبان", "语言"),
        "Latency" to Triple("Latency", "تاخیر (پینگ)", "延迟"),
        "Latency %s ms" to Triple("Latency %s ms", "تاخیر %s میلی‌ثانیه", "延迟 %s 毫秒"),
        "Latency n/a" to Triple("Latency n/a", "تاخیر نامشخص", "延迟 不可用"),
        "Latency —" to Triple("Latency —", "تأخیر —", "延迟 —"),
        "Latency …" to Triple("Latency …", "تاخیر …", "延迟 …"),
        "Later" to Triple("Later", "بعداً", "稍后"),
        "Latvia" to Triple("Latvia", "لتوانی", "拉脱维亚"),
        "Let other devices use this tunnel" to Triple("Let other devices use this tunnel", "اجازه به سایر دستگاه‌ها برای استفاده از این تونل", "允许其他设备使用此隧道"),
        "Light" to Triple("Light", "سبک", "浅色模式"),
        "Light — theme" to Triple("Light", "روشن", "浅色模式"),
        "Lithuania" to Triple("Lithuania", "لیتوانی", "立陶宛"),
        "Local network access" to Triple("Local network access", "دسترسی به شبکه محلی", "局域网访问"),
        "Log" to Triple("Log", "گزارش‌های سیستم (Log)", "日志"),
        "Log verbosity" to Triple("Log verbosity", "جزئیات گزارش‌ها", "日志详细度"),
        "Logs" to Triple("Logs", "گزارش‌های سیستم", "运行日志"),
        "Low" to Triple("Low", "پایین", "低性能"),
        "Lower overhead on mild filtering" to Triple("Lower overhead on mild filtering", "بار پردازشی کمتر برای فیلترینگ ضعیف", "资源占用低，适用于轻度审查网络"),
        "Luxembourg" to Triple("Luxembourg", "لوکزامبورگ", "卢森堡"),
        "MASQUE" to Triple("MASQUE", "ماسک", "MASQUE"),
        "MASQUE TRANSPORT" to Triple("MASQUE TRANSPORT", "حمل MASQUE", "MASQUE 传输"),
        "MODE" to Triple("MODE", "حالت", "模式"),
        "MSN-GUARD" to Triple("MSN-GUARD", "MSN-GUARD", "MSN-GUARD"),
        "MSN-GUARD %s has been released. You are on %s." to Triple("MSN-GUARD %s has been released. You are on %s.", "نسخه %s MSN-GUARD منتشر شده است. نسخه فعلی شما %s است.", "MSN-GUARD %s 已发布，当前版本为 %s。"),
        "MSN-GUARD %s is installed" to Triple("MSN-GUARD %s is installed", "نسخه %s MSN-GUARD نصب شده است", "已安装 MSN-GUARD %s"),
        "MSN-GUARD \\\${appVersion()}" to Triple("MSN-GUARD \\\${appVersion()}", "MSN-GUARD \\\${appVersion()}", "MSN-GUARD \\\${appVersion()}"),
        "MSN-GUARD is running" to Triple("MSN-GUARD is running", "MSN-GUARD در حال اجراست", "MSN-GUARD 正在运行"),
        "MSN-GUARD log" to Triple("MSN-GUARD log", "گزارش MSN-GUARD", "MSN-GUARD 日志"),
        "Malaysia" to Triple("Malaysia", "مالزی", "马来西亚"),
        "Manual bridge" to Triple("Manual bridge", "پل دستی (Bridge)", "手动网桥"),
        "Manual endpoint" to Triple("Manual endpoint", "نقطه پایانی دستی", "手动 Endpoint"),
        "Medium" to Triple("Medium", "متوسط", "中等"),
        "Meek" to Triple("Meek", "پل Meek", "Meek 网桥"),
        "Mexico" to Triple("Mexico", "مکزیک", "墨西哥"),
        "Moderate hardware" to Triple("Moderate hardware", "سخت‌افزار متوسط", "适用于主流设备"),
        "Moldova" to Triple("Moldova", "مولداوی", "摩尔多瓦"),
        "N/A" to Triple("N/A", "نامرتبط", "不适用"),
        "Netherlands" to Triple("Netherlands", "هلند", "荷兰"),
        "New Zealand" to Triple("New Zealand", "نیوزیلند", "新西兰"),
        "No bridge; fastest where Tor is not blocked" to Triple("No bridge; fastest where Tor is not blocked", "بدون پل (Bridge)؛ سریع‌ترین حالت در شبکه‌های بدون مسدودی تور", "不使用网桥；在 Tor 未被封锁的网络中速度最快"),
        "No browser found" to Triple("No browser found", "مرورگری پیدا نشد", "未找到浏览器"),
        "No compatible release was found" to Triple("No compatible release was found", "نسخه سازگاری پیدا نشد", "未找到兼容版本"),
        "No connection events yet" to Triple("No connection events yet", "هنوز رویدادی ثبت نشده است", "暂无连接事件"),
        "No data yet" to Triple("No data yet", "هنوز داده‌ای نیست", "暂无数据"),
        "No local network — turn on the hotspot or join Wi-Fi" to Triple("No local network — turn on the hotspot or join Wi-Fi", "شبکه محلی نیست — هات‌اسپات را روشن کنید یا به وای‌فای وصل شوید", "无局域网 — 请开启热点或连接 Wi-Fi"),
        "No traffic-shape padding" to Triple("No traffic-shape padding", "بدون پدینگ شکل‌دهی ترافیک", "不进行数据包混淆填充"),
        "No transport connected on this network — try again or pick one yourself" to Triple("No transport connected on this network — try again or pick one yourself", "هیچ حملی روی این شبکه وصل نشد — دوباره امتحان کن یا خودت یکی را انتخاب کن", "此网络上没有传输方式可用 — 请重试或自行选择"),
        "No update available" to Triple("No update available", "بروزرسانی در دسترس نیست", "暂无更新"),
        "Node list" to Triple("Node list", "لیست نودها", "节点列表"),
        "Norway" to Triple("Norway", "نروژ", "挪威"),
        "Not connected" to Triple("Not connected", "متصل نیست", "未连接"),
        "Not set" to Triple("Not set", "تنظیم‌نشده", "未设置"),
        "Not used in SOCKS mode" to Triple("Not used in SOCKS mode", "در حالت SOCKS استفاده نمی‌شود", "SOCKS 模式下不使用"),
        "Nothing saved yet" to Triple("Nothing saved yet", "هنوز چیزی ذخیره نشده است", "尚未保存任何内容"),
        "Numbers only" to Triple("Numbers only", "فقط عدد", "仅限数字"),
        "Numeric IPv4 or bracketed IPv6 address with port. Bypasses discovery." to Triple("Numeric IPv4 or bracketed IPv6 address with port. Bypasses discovery.", "آدرس عددی IPv4 یا IPv6 داخل کروشه به همراه پورت. فرایند شناسایی خودکار را دور می‌زند.", "请输入带端口的 IPv4 地址或带方括号的 IPv6 地址。填入后将跳过自动探测。"),
        "OFF" to Triple("OFF", "خاموش", "关"),
        "OK" to Triple("OK", "تایید", "确定"),
        "ON" to Triple("ON", "روشن", "开"),
        "Obfuscation" to Triple("Obfuscation", "مخفی‌سازی ترافیک", "流量混淆"),
        "Off" to Triple("Off", "خاموش", "关闭"),
        "On" to Triple("On", "روشن", "开启"),
        "On · not effective on this network" to Triple("On · not effective on this network", "روشن · در این شبکه مؤثر نیست", "开 · 在此网络无效"),
        "On · tuned for this network" to Triple("On · tuned for this network", "روشن · تنظیم برای این شبکه", "开 · 已针对此网络调优"),
        "On · will measure this network" to Triple("On · will measure this network", "روشن · این شبکه اندازه‌گیری می‌شود", "开 · 将测量此网络"),
        "One bridge per line, exactly as you received it. obfs4, meek_lite, webtunnel and snowflake are supported, as is a plain IP:port." to Triple("One bridge per line, exactly as you received it. obfs4, meek_lite, webtunnel and snowflake are supported, as is a plain IP:port.", "در هر خط یک پل وارد کنید، دقیقاً همان‌طور که دریافت کرده‌اید. پشتیبانی از obfs4، meek_lite، webtunnel، snowflake و همچنین IP:port ساده.", "每行输入一个完整网桥地址。支持 obfs4、meek_lite、webtunnel、snowflake 以及普通 IP:端口 格式。"),
        "Onion routing" to Triple("Onion routing", "مسیریابی پیازی", "洋葱路由"),
        "Onion routing; slowest but hardest to block" to Triple("Onion routing; slowest but hardest to block", "مسیریابی پیازی؛ کندترین اما سخت‌ترین حالت برای مسدودسازی", "洋葱路由；速度较慢但具备极强抗封锁能力"),
        "Only %s selected app" to Triple("Only %s selected app", "فقط %s برنامه انتخاب‌شده", "仅 %s 个应用已选"),
        "Only %s selected app%s" to Triple("Only %s selected app%s", "فقط %s برنامه انتخاب‌شده%s", "仅 %s 个应用已选%s"),
        "Only %s selected apps" to Triple("Only %s selected apps", "فقط %s برنامه انتخاب‌شده", "仅 %s 个应用已选"),
        "Only 1 selected app" to Triple("Only 1 selected app", "فقط ۱ برنامه انتخاب‌شده", "仅 1 个所选应用"),
        "Only apps you point at the port · not Tor or SHARD" to Triple("Only apps you point at the port · not Tor or SHARD", "فقط برنامه‌هایی که به این پورت متصل شوند · به جز تور یا شارد", "仅代理指向指定端口的应用（Tor 和 SHARD 除外）"),
        "Only errors" to Triple("Only errors", "فقط خطاهای حیاتی", "仅记录严重错误"),
        "Only for MASQUE and WireGuard" to Triple("Only for MASQUE and WireGuard", "فقط مخصوص ماسک و وایرگارد", "仅适用于 MASQUE 与 WireGuard"),
        "Only selected apps" to Triple("Only selected apps", "فقط برنامه‌های انتخاب‌شده", "仅限选中应用"),
        "Outer transport" to Triple("Outer transport", "پروتکل انتقال بیرونی", "外层传输协议"),
        "P-256 and X25519 only" to Triple("P-256 and X25519 only", "فقط منحنی‌های P-256 و X25519", "仅使用 P-256 与 X25519"),
        "PROTECTION" to Triple("PROTECTION", "امنیت و حفاظت", "防护"),
        "PSIPHON" to Triple("PSIPHON", "سایفون", "赛风"),
        "PSIPHON OVER WARP" to Triple("PSIPHON OVER WARP", "سایفون روی وارپ", "Psiphon over WARP"),
        "Packet pattern is too long" to Triple("Packet pattern is too long", "الگوی پکت بیش از حد بلند است", "数据包模式过长"),
        "Pause" to Triple("Pause", "توقف", "暂停"),
        "Performance" to Triple("Performance", "عملکرد", "性能模式"),
        "Ping unavailable" to Triple("Ping unavailable", "پینگ در دسترس نیست", "Ping 不可用"),
        "Poland" to Triple("Poland", "لهستان", "波兰"),
        "Porcelain — grey page, white cards" to Triple("Porcelain — grey page, white cards", "چینی — صفحه خاکستری، کارت‌های سفید", "陶瓷白 — 灰底白卡片风格"),
        "Portugal" to Triple("Portugal", "پرتغال", "葡萄牙"),
        "Preferred country" to Triple("Preferred country", "کشور ترجیحی", "首选国家/地区"),
        "Preferred exit country cleared — Psiphon chooses" to Triple("Preferred exit country cleared — Psiphon chooses", "کشور خروجی ترجیحی پاک شد — انتخاب با سایفون", "首选出口国家已清除 — 由 Psiphon 选择"),
        "Preparing WireGuard tunnel" to Triple("Preparing WireGuard tunnel", "آماده‌سازی تونل وایرگارد", "正在准备 WireGuard 隧道"),
        "Preparing \\\${selectedProtocol.label} tunnel" to Triple("Preparing \\\${selectedProtocol.label} tunnel", "آماده‌سازی تانل \\\${selectedProtocol.label}", "正在准备 \\\${selectedProtocol.label} 隧道"),
        "Preset" to Triple("Preset", "از پیش تنظیم‌شده", "预设"),
        "Psiphon" to Triple("Psiphon", "سایفون", "Psiphon"),
        "Psiphon SOCKS port unavailable" to Triple("Psiphon SOCKS port unavailable", "پورت سایفون در دسترس نیست", "赛风 SOCKS 端口不可用"),
        "Psiphon over WARP" to Triple("Psiphon over WARP", "سایفون روی وارپ", "Psiphon over WARP"),
        "Psiphon starting..." to Triple("Psiphon starting...", "سایفون در حال راه‌اندازی…", "赛风正在启动…"),
        "Psiphon tries this country first. If it will not connect, all countries are tried." to Triple("Psiphon tries this country first. If it will not connect, all countries are tried.", "سایفون ابتدا اتصال به این کشور را امتحان می‌کند. در صورت عدم اتصال، همه کشورها بررسی می‌شوند.", "Psiphon 将优先连接此国家/地区。若连接失败，将自动尝试其他地区。"),
        "Public nodes, auto-selected; no setup" to Triple("Public nodes, auto-selected; no setup", "نودهای عمومی، انتخاب خودکار؛ بدون نیاز به تنظیمات", "公共节点，自动选择，即插即用"),
        "QUIC first; falls back to HTTP/2 if UDP is blocked" to Triple("QUIC first; falls back to HTTP/2 if UDP is blocked", "اول QUIC؛ اگر UDP بلاک بود به HTTP/2 برمی‌گردد", "QUIC 优先；UDP 被封时回退 HTTP/2"),
        "QUIC; best on healthy UDP networks" to Triple("QUIC; best on healthy UDP networks", "QUIC؛ بهترین روی شبکه‌های UDP سالم", "QUIC；在 UDP 正常的网络上最佳"),
        "Quiet, patient probing" to Triple("Quiet, patient probing", "بررسی آرام و کم‌صدا", "低频耐心探测，降低被审查风险"),
        "RETRY" to Triple("RETRY", "تلاش مجدد", "RETRY"),
        "ROUTING" to Triple("ROUTING", "مسیریابی", "路由"),
        "ROUTING & DATA" to Triple("ROUTING & DATA", "مسیریابی و داده‌ها", "路由与数据"),
        "Re-measure network" to Triple("Re-measure network", "سنجش مجدد شبکه", "重新评估网络状态"),
        "Reach printers, NAS and your router while connected" to Triple("Reach printers, NAS and your router while connected", "دسترسی به پرینتر، NAS و روتر در زمان اتصال", "连接时仍可访问打印机、NAS 和路由器"),
        "Recommended filtering resistance" to Triple("Recommended filtering resistance", "مقاومت پیشنهادی در برابر فیلترینگ", "推荐设置，兼顾速度与抗封锁能力"),
        "Reconnect" to Triple("Reconnect", "اتصال مجدد", "重连"),
        "Reconnect automatically if the tunnel drops" to Triple("Reconnect automatically if the tunnel drops", "اتصال مجدد خودکار در صورت قطعی ارتباط", "隧道断开时自动重连"),
        "Reconnect timed out — tap the dial to connect" to Triple("Reconnect timed out — tap the dial to connect", "اتصال مجدد طول کشید — روی دکمه بزنید", "重新连接超时 — 点击拨盘连接"),
        "Reconnecting after %s…" to Triple("Reconnecting after %s…", "اتصال مجدد بعد از %s…", "因 %s 正在重新连接…"),
        "Reconnecting after \\\$reason…" to Triple("Reconnecting after \\\$reason…", "اتصال مجدد بعد از \\\$reason…", "因 \\\$reason 正在重新连接…"),
        "Reconnecting…" to Triple("Reconnecting…", "در حال اتصال مجدد…", "正在重新连接…"),
        "Remove saved gateway latency data" to Triple("Remove saved gateway latency data", "حذف داده‌های تاخیر (Latency) درگاه‌های ذخیره‌شده", "删除已保存网关的延迟数据"),
        "Reset" to Triple("Reset", "بازنشانی", "重置"),
        "Reset to defaults" to Triple("Reset to defaults", "بازنشانی به تنظیمات اولیه", "恢复默认设置"),
        "Restore settings" to Triple("Restore settings", "بازیابی تنظیمات", "恢复设置"),
        "Restored %s settings from v%s" to Triple("Restored %s settings from v%s", "%s تنظیم از نسخه v%s بازیابی شد", "已从 v%s 恢复 %s 项设置"),
        "Restored \\\${outcome.restored} settings from v\\\${outcome.version}" to Triple("Restored \\\${outcome.restored} settings from v\\\${outcome.version}", "\\\${outcome.restored} تنظیم از نسخه v\\\${outcome.version} بازگردانی شد", "已从 v\\\${outcome.version} 恢复 \\\${outcome.restored} 项设置"),
        "Resume" to Triple("Resume", "ادامه", "继续"),
        "Rides a CDN; slow but hard to block" to Triple("Rides a CDN; slow but hard to block", "عبور از شبکه CDN؛ کند اما بسیار مقاوم در برابر مسدودسازی", "基于 CDN 伪装；速度较慢但极难被封锁"),
        "Romania" to Triple("Romania", "رومانی", "罗马尼亚"),
        "Routers and constrained devices" to Triple("Routers and constrained devices", "روترها و دستگاه‌های با منابع محدود", "适用于路由器或低配设备"),
        "SCAN MODE" to Triple("SCAN MODE", "حالت اسکن", "扫描模式"),
        "SECURED BY MSN-GUARD" to Triple("SECURED BY MSN-GUARD", "ایمن‌شده توسط MSN-GUARD", "由 MSN-GUARD 提供安全保护"),
        "SELECTED" to Triple("SELECTED", "انتخاب‌شده", "已选择"),
        "SESSION" to Triple("SESSION", "زمان اتصال", "连接时长"),
        "SHARD" to Triple("SHARD", "شارد", "SHARD"),
        "SHARD connected via %s" to Triple("SHARD connected via %s", "شارد وصل شد از طریق %s", "SHARD 已通过 %s 连接"),
        "SHARD connected via \\\$node" to Triple("SHARD connected via \\\$node", "شارد وصل شد از طریق \\\$node", "SHARD 已通过 \\\$node 连接"),
        "SHARD runs as a VPN — use Share over LAN instead" to Triple("SHARD runs as a VPN — use Share over LAN instead", "شارد به‌صورت VPN اجرا می‌شود — به‌جایش اشتراک با LAN را استفاده کن", "SHARD 以 VPN 方式运行 — 请改用 LAN 共享"),
        "SHARD runs as a VPN, not a SOCKS proxy — set Tunnel type back to " to Triple("SHARD runs as a VPN, not a SOCKS proxy — set Tunnel type back to ", "شارد به‌صورت VPN اجرا می‌شود نه پروکسی SOCKS — نوع تانل را به VPN برگردان؛ اشتراک با LAN آنجا کار می‌کند", "SHARD 以 VPN 方式运行，而非 SOCKS 代理 — 请将隧道类型改回 VPN；LAN 共享在该模式下可用"),
        "SHARD shares from VPN mode — set Tunnel type to VPN" to Triple("SHARD shares from VPN mode — set Tunnel type to VPN", "شارد از حالت VPN به اشتراک می‌گذارد — نوع تونل را روی VPN بگذارید", "SHARD 在 VPN 模式下共享 — 请将隧道类型设为 VPN"),
        "SHARE" to Triple("SHARE", "اشتراک‌گذاری", "分享"),
        "SMART SPLIT" to Triple("SMART SPLIT", "تفکیک هوشمند", "智能分流"),
        "SOCKS port" to Triple("SOCKS port", "پورت SOCKS", "SOCKS 端口"),
        "SOCKS port set to %s" to Triple("SOCKS port set to %s", "پورت SOCKS روی %s تنظیم شد", "SOCKS 端口已设为 %s"),
        "SOCKS port set to %s — applies on the next connect" to Triple("SOCKS port set to %s — applies on the next connect", "پورت SOCKS روی %s تنظیم شد — در اتصال بعدی اعمال می‌شود", "SOCKS 端口已设为 %s — 下次连接时生效"),
        "SOCKS port set to \\\$typed" to Triple("SOCKS port set to \\\$typed", "پورت SOCKS روی \\\$typed تنظیم شد", "SOCKS 端口已设为 \\\$typed"),
        "SOCKS proxy" to Triple("SOCKS proxy", "پروکسی SOCKS", "SOCKS 代理"),
        "SOCKS proxy mode cannot use Tor — switch to another transport, " to Triple("SOCKS proxy mode cannot use Tor — switch to another transport, ", "حالت پروکسی SOCKS نمی‌تواند تور را اجرا کند — یک حمل دیگر را انتخاب کن، یا نوع تانل را به VPN برگردان", "SOCKS 代理模式无法运行 Tor — 请选择其他传输方式，或将隧道类型改回 VPN"),
        "SOCKS proxy on %s" to Triple("SOCKS proxy on %s", "پروکسی SOCKS روی %s", "SOCKS 代理端口 %s"),
        "SOCKS proxy on %s · over WARP" to Triple("SOCKS proxy on %s · over WARP", "پروکسی SOCKS روی %s · روی وارپ", "%s 上的 SOCKS 代理 · over WARP"),
        "SOCKS5 %s · HTTP %s · no password" to Triple("SOCKS5 %s · HTTP %s · no password", "SOCKS5 %s · HTTP %s · بدون رمز", "SOCKS5 %s · HTTP %s · 无密码"),
        "SOCKS5 proxy tunnel" to Triple("SOCKS5 proxy tunnel", "تانل پروکسی SOCKS5", "SOCKS5 代理隧道"),
        "SPEED" to Triple("SPEED", "سرعت", "实时速率"),
        "Save" to Triple("Save", "ذخیره", "保存"),
        "Saved — applies on the next connect" to Triple("Saved — applies on the next connect", "ذخیره شد — در اتصال بعدی اعمال می‌شود", "已保存 — 下次连接时生效"),
        "Saved — set Connection mode to Manual bridge to use it" to Triple("Saved — set Connection mode to Manual bridge to use it", "ذخیره شد — برای استفاده، حالت اتصال را روی پل دستی بگذار", "已保存 — 请将连接模式设为手动网桥后使用"),
        "Scale scan concurrency and buffers to match your hardware" to Triple("Scale scan concurrency and buffers to match your hardware", "تنظیم همزمانی اسکن و بافرها متناسب با سخت‌افزار شما", "根据设备硬件性能调整并发扫描与缓冲区"),
        "Scan IPv4 and IPv6 endpoints" to Triple("Scan IPv4 and IPv6 endpoints", "اسکن همزمان نقاط پایانی IPv4 و IPv6", "同时扫描 IPv4 与 IPv6 节点"),
        "Scan IPv4 endpoints only" to Triple("Scan IPv4 endpoints only", "اسکن اختصاصی نقاط پایانی IPv4", "仅扫描 IPv4 节点"),
        "Scan IPv6 endpoints only" to Triple("Scan IPv6 endpoints only", "اسکن اختصاصی نقاط پایانی IPv6", "仅扫描 IPv6 节点"),
        "Scan Mode" to Triple("Scan Mode", "حالت اسکن", "扫描模式"),
        "Scanner options" to Triple("Scanner options", "تنظیمات اسکنر", "扫描器设置"),
        "Scanning" to Triple("Scanning", "در حال اسکن", "正在扫描"),
        "Scanning installed apps…" to Triple("Scanning installed apps…", "در حال اسکن اپ‌های نصب‌شده…", "正在扫描已安装的应用…"),
        "Search apps…" to Triple("Search apps…", "جستجوی برنامه‌ها…", "搜索应用…"),
        "Searching…" to Triple("Searching…", "در حال جستجو…", "搜索中…"),
        "Select apps to exclude" to Triple("Select apps to exclude", "برنامه‌ها را برای استثنا از تونل انتخاب کنید", "选择绕过隧道的应用"),
        "Select apps to include" to Triple("Select apps to include", "برنامه‌ها را برای استفاده از تونل انتخاب کنید", "选择走隧道的应用"),
        "Serbia" to Triple("Serbia", "صربستان", "塞尔维亚"),
        "Set Tunnel type to SOCKS proxy first" to Triple("Set Tunnel type to SOCKS proxy first", "اول نوع تانل را روی پروکسی SOCKS بگذار", "请先将隧道类型设为 SOCKS 代理"),
        "Set Tunnel type to SOCKS proxy to share %s" to Triple("Set Tunnel type to SOCKS proxy to share %s", "برای اشتراک %s، نوع تونل را روی پروکسی SOCKS بگذارید", "要共享 %s，请将隧道类型设为 SOCKS 代理"),
        "Settings" to Triple("Settings", "تنظیمات", "设置"),
        "Settings reset to defaults" to Triple("Settings reset to defaults", "تنظیمات به پیش‌فرض برگشت", "设置已恢复为默认值"),
        "Settings saved — this file holds no passwords" to Triple("Settings saved — this file holds no passwords", "تنظیمات ذخیره شد — این فایل هیچ رمز عبوری ندارد", "设置已保存 — 此文件不含任何密码"),
        "Shaping · Anti-DPI" to Triple("Shaping · Anti-DPI", "شکل‌دهی ترافیک · ضد DPI", "流量塑形 · 抗 DPI"),
        "Share log" to Triple("Share log", "اشتراک‌گذاری گزارش", "分享日志"),
        "Share over LAN" to Triple("Share over LAN", "اشتراک‌گذاری در شبکه محلی (LAN)", "LAN 共享"),
        "Singapore" to Triple("Singapore", "سنگاپور", "新加坡"),
        "Single WARP tunnel; blocked on some carriers" to Triple("Single WARP tunnel; blocked on some carriers", "تونل تک‌لایه وارپ؛ ممکن است در برخی اپراتورها مسدود باشد", "单层 WARP 隧道；部分运营商可能封锁"),
        "Slovakia" to Triple("Slovakia", "اسلواکی", "斯洛伐克"),
        "Smart Split" to Triple("Smart Split", "تفکیک هوشمند (Smart Split)", "智能分流"),
        "Snowflake" to Triple("Snowflake", "پل Snowflake", "Snowflake"),
        "Source on GitHub" to Triple("Source on GitHub", "سورس‌کد در گیت‌هاب", "GitHub 开源项目"),
        "Telegram Channel" to Triple("Telegram Channel", "کانال تلگرام", "Telegram 频道"),
        "South Africa" to Triple("South Africa", "آفریقای جنوبی", "南非"),
        "South Korea" to Triple("South Korea", "کره جنوبی", "韩国"),
        "Spain" to Triple("Spain", "اسپانیا", "西班牙"),
        "Split tunneling" to Triple("Split tunneling", "میان‌بر زدن تونل", "应用分流"),
        "Standard TLS handshake" to Triple("Standard TLS handshake", "دست‌تکانی استاندارد TLS", "使用标准 TLS 握手"),
        "Start a new scan every connection" to Triple("Start a new scan every connection", "شروع اسکن جدید در هر اتصال", "每次连接时重新发起全量扫描"),
        "Starting" to Triple("Starting", "در حال راه‌اندازی", "正在启动"),
        "Starting %s tunnel" to Triple("Starting %s tunnel", "در حال راه‌اندازی تونل %s", "正在启动 %s 隧道"),
        "Starting \\\$currentProtocol…" to Triple("Starting \\\$currentProtocol…", "راه‌اندازی \\\$currentProtocol…", "正在启动 \\\$currentProtocol…"),
        "Starting device routing…" to Triple("Starting device routing…", "راه‌اندازی مسیریابی دستگاه…", "正在启动设备路由…"),
        "Stealth" to Triple("Stealth", "پنهان‌کارانه", "隐蔽模式"),
        "Strict" to Triple("Strict", "سخت‌گیرانه", "严格"),
        "Strict CONNECT-IP verification before selection" to Triple("Strict CONNECT-IP verification before selection", "تایید سخت‌گیرانه CONNECT-IP قبل از انتخاب", "选择前执行严格的 CONNECT-IP 连通性校验"),
        "Sweden" to Triple("Sweden", "سوئد", "瑞典"),
        "Switching to another node…" to Triple("Switching to another node…", "در حال تعویض گره…", "正在切换节点…"),
        "Switzerland" to Triple("Switzerland", "سوئیس", "瑞士"),
        "TAP TO CONNECT" to Triple("TAP TO CONNECT", "برای اتصال لمس کنید", "点击连接"),
        "TCP with TLS fragmentation; use on restricted networks" to Triple("TCP with TLS fragmentation; use on restricted networks", "TCP با قطعه‌قطعه‌سازی TLS؛ برای شبکه‌های محدود", "TCP 加 TLS 分片；用于受限网络"),
        "TCP; use when UDP or QUIC is blocked" to Triple("TCP; use when UDP or QUIC is blocked", "TCP؛ وقتی UDP یا QUIC بلاک است", "TCP；在 UDP 或 QUIC 被封时使用"),
        "THIS MONTH" to Triple("THIS MONTH", "این ماه", "本月流量"),
        "THIS SESSION" to Triple("THIS SESSION", "این نشست", "本次连接"),
        "TLS fingerprint" to Triple("TLS fingerprint", "اثرانگشت TLS", "TLS 指纹"),
        "TLS fragmentation" to Triple("TLS fragmentation", "تکه‌تکه‌سازی TLS", "TLS 分片"),
        "TOR" to Triple("TOR", "تور", "Tor"),
        "TOR OVER WARP" to Triple("TOR OVER WARP", "تور روی وارپ", "Tor over WARP"),
        "TROUBLESHOOTING" to Triple("TROUBLESHOOTING", "عیب‌یابی", "故障排除"),
        "Taiwan" to Triple("Taiwan", "تایوان", "台湾"),
        "Tap the dial to connect" to Triple("Tap the dial to connect", "برای اتصال، دکمه را لمس کنید", "点击拨盘进行连接"),
        "Tap to download" to Triple("Tap to download", "برای دانلود بزنید", "点按下载"),
        "Tapping Update opens the download in your browser. Open the downloaded file to install it." to Triple("Tapping Update opens the download in your browser. Open the downloaded file to install it.", "با زدن بروزرسانی، دانلود در مرورگر شما باز می‌شود. برای نصب، فایل دانلودشده را باز کنید.", "点击“更新”将在浏览器打开下载页。下载完成后请打开文件安装。"),
        "The %s tunnel carrying %s dropped" to Triple("The %s tunnel carrying %s dropped", "تانل %s که %s را حمل می‌کرد قطع شد", "承载 %s 的 %s 隧道已断开"),
        "The \\\$label tunnel carrying \\\$inner dropped" to Triple("The \\\$label tunnel carrying \\\$inner dropped", "تانل \\\$label که \\\$inner را حمل می‌کرد قطع شد", "承载 \\\$inner 的 \\\$label 隧道已断开"),
        "The backup was not ready — try again" to Triple("The backup was not ready — try again", "پشتیبان آماده نبود — دوباره امتحان کن", "备份尚未就绪 — 请重试"),
        "The original console — black glass and neon" to Triple("The original console — black glass and neon", "کنسول اصلی — شیشه مشکی و نئون", "经典极客 — 黑色玻璃与霓虹风"),
        "Theme" to Triple("Theme", "پوسته (تم)", "主题外观"),
        "This IP is already applied" to Triple("This IP is already applied", "این آی‌پی قبلاً اعمال شده است", "该 IP 已应用"),
        "This IP will replace all node addresses in SHARD configs" to Triple("This IP will replace all node addresses in SHARD configs", "این آی‌پی جایگزین آدرس تمام نودها در کانفیگ‌های شارد می‌شود", "此 IP 将替换 SHARD 配置中的所有节点地址"),
        "This device has no file picker" to Triple("This device has no file picker", "این دستگاه انتخابگر فایل ندارد", "此设备没有文件选择器"),
        "This file is not a settings backup" to Triple("This file is not a settings backup", "این فایل پشتیبان تنظیمات نیست", "此文件不是设置备份"),
        "Thorough" to Triple("Thorough", "دقیق و کامل", "深度模式"),
        "Tor" to Triple("Tor", "تور", "Tor"),
        "Tor cannot run as a SOCKS proxy — pick another transport" to Triple("Tor cannot run as a SOCKS proxy — pick another transport", "تور نمی‌تواند پروکسی SOCKS باشد — یک حمل دیگر انتخاب کن", "Tor 无法作为 SOCKS 代理运行 — 请选择其他传输方式"),
        "Tor cannot run as a SOCKS proxy — set Tunnel type to VPN" to Triple("Tor cannot run as a SOCKS proxy — set Tunnel type to VPN", "تور نمی‌تواند پروکسی SOCKS باشد — نوع تونل را روی VPN بگذارید", "Tor 无法作为 SOCKS 代理 — 请将隧道类型设为 VPN"),
        "Tor connected via %s" to Triple("Tor connected via %s", "تور وصل شد از طریق %s", "Tor 已通过 %s 连接"),
        "Tor connected via \\\$via" to Triple("Tor connected via \\\$via", "تور وصل شد از طریق \\\$via", "Tor 已通过 \\\$via 连接"),
        "Tor connection mode set to Auto" to Triple("Tor connection mode set to Auto", "حالت اتصال تور روی خودکار رفت", "Tor 连接模式已设为自动"),
        "Tor could not connect over %s; try Auto" to Triple("Tor could not connect over %s; try Auto", "تور از طریق %s وصل نشد؛ حالت خودکار را امتحان کنید", "Tor 无法经 %s 连接；请尝试自动"),
        "Tor could not connect through %s; turn Tor over WARP off to try obfs4 and Snowflake" to Triple("Tor could not connect through %s; turn Tor over WARP off to try obfs4 and Snowflake", "تور از طریق %s وصل نشد؛ تور روی وارپ را خاموش کنید تا obfs4 و Snowflake امتحان شوند", "Tor 无法经 %s 连接；请关闭 Tor over WARP 以尝试 obfs4 和 Snowflake"),
        "Tor could not connect with any method on this network" to Triple("Tor could not connect with any method on this network", "تور با هیچ روشی روی این شبکه وصل نشد", "Tor 在此网络无法以任何方式连接"),
        "Tor exit country cleared — Tor chooses" to Triple("Tor exit country cleared — Tor chooses", "کشور خروجی تور پاک شد — انتخاب با تور", "Tor 出口国家已清除 — 由 Tor 选择"),
        "Tor over WARP" to Triple("Tor over WARP", "تور روی وارپ", "Tor over WARP"),
        "Tor tries to exit here. If it cannot, another country is used." to Triple("Tor tries to exit here. If it cannot, another country is used.", "تور تلاش می‌کند از این کشور خارج شود. در صورت عدم امکان، کشور دیگری استفاده می‌شود.", "Tor 将优先从该国家/地区的节点出口。若不可用，将自动切换至其他地区。"),
        "Tor%s" to Triple("Tor%s", "تور%s", "Tor%s"),
        "Tor%s over WARP" to Triple("Tor%s over WARP", "تور%s روی وارپ", "Tor%s over WARP"),
        "Trace" to Triple("Trace", "ردیابی دقیق (Trace)", "追踪 (Trace)"),
        "Traffic carried by MSN-GUARD. Per-app attribution is not available from encrypted tunnel counters." to Triple("Traffic carried by MSN-GUARD. Per-app attribution is not available from encrypted tunnel counters.", "ترافیک عبوری از MSN-GUARD. آمار تفکیکی برنامه‌ها در شمارنده‌های تونل رمزنگاری‌شده در دسترس نیست.", "MSN-GUARD 传输的总流量。由于加密隧道的特性，无法提供单个应用的流量统计。"),
        "Traffic monitor" to Triple("Traffic monitor", "مدیریت مصرف ترافیک", "流量监控"),
        "Tries each method until one connects" to Triple("Tries each method until one connects", "تلاش برای برقراری اتصال با امتحان تک‌تک روش‌ها", "轮询所有方式直到连通"),
        "Try MASQUE, then WireGuard, then WoW — remembers what works" to Triple("Try MASQUE, then WireGuard, then WoW — remembers what works", "امتحان MASQUE، سپس WireGuard، سپس WoW — حالت موفق را به خاطر می‌سپارد", "依次尝试 MASQUE、WireGuard、WoW，并记住最佳通道"),
        "Try again later" to Triple("Try again later", "بعداً دوباره امتحان کنید", "稍后再试"),
        "Try saved gateways first" to Triple("Try saved gateways first", "ابتدا امتحان درگاه‌های ذخیره‌شده", "优先尝试已保存的网关"),
        "Trying %s" to Triple("Trying %s", "در حال امتحان %s", "正在尝试 %s"),
        "Trying \\\${next.label}..." to Triple("Trying \\\${next.label}...", "در حال امتحان \\\${next.label}…", "正在尝试 \\\${next.label}…"),
        "Trying \\\${protocol.label}…" to Triple("Trying \\\${protocol.label}…", "در حال امتحان \\\${protocol.label}…", "正在尝试 \\\${protocol.label}…"),
        "Trying all countries…" to Triple("Trying all countries…", "در حال امتحان همه کشورها…", "正在尝试所有国家…"),
        "Tunnel" to Triple("Tunnel", "تونل", "隧道"),
        "Tunnel Psiphon inside a WARP transport" to Triple("Tunnel Psiphon inside a WARP transport", "تونل‌زنی سایفون در بستر وارپ", "将赛风封装在 WARP 传输内"),
        "Tunnel and VPN events" to Triple("Tunnel and VPN events", "رویدادهای تونل و وی‌پی‌ان", "隧道与 VPN 事件记录"),
        "Tunnel controls" to Triple("Tunnel controls", "کنترل‌های تونل", "隧道控制"),
        "Tunnel handshake succeeded but no traffic passes — try another protocol" to Triple("Tunnel handshake succeeded but no traffic passes — try another protocol", "هندشیک تانل موفق شد ولی هیچ ترافیکی رد نمی‌شود — یک پروتکل دیگر را امتحان کن", "隧道握手成功但无流量通过 — 请尝试其他协议"),
        "Tunnel internals" to Triple("Tunnel internals", "جزئیات داخلی تونل", "记录隧道内部运行细节"),
        "Tunnel is active; HTTP health check failed" to Triple("Tunnel is active; HTTP health check failed", "تونل فعال است؛ بررسی سلامت HTTP ناموفق بود", "隧道已运行；HTTP 健康检查失败"),
        "Tunnel is up but no traffic is passing" to Triple("Tunnel is up but no traffic is passing", "تونل بالا آمده اما ترافیکی عبور نمی‌کند", "隧道已建立但没有流量通过"),
        "Tunnel stopped unexpectedly" to Triple("Tunnel stopped unexpectedly", "تانل به‌طور غیرمنتظره متوقف شد", "隧道意外停止"),
        "Tunnel type" to Triple("Tunnel type", "نوع تونل", "隧道类型"),
        "Turbo" to Triple("Turbo", "توربو (سریع)", "极速模式"),
        "Türkiye" to Triple("Türkiye", "ترکیه", "土耳其"),
        "UP" to Triple("UP", "آپلود", "上传"),
        "Ukraine" to Triple("Ukraine", "اوکراین", "乌克兰"),
        "United Arab Emirates" to Triple("United Arab Emirates", "امارات", "阿联酋"),
        "United Kingdom" to Triple("United Kingdom", "بریتانیا", "英国"),
        "United States" to Triple("United States", "آمریکا", "美国"),
        "Update" to Triple("Update", "بروزرسانی", "更新"),
        "Update available" to Triple("Update available", "بروزرسانی در دسترس است", "有可用更新"),
        "Update check failed" to Triple("Update check failed", "بررسی بروزرسانی ناموفق بود", "检查更新失败"),
        "Updating…" to Triple("Updating…", "در حال بروزرسانی…", "正在更新…"),
        "Upload" to Triple("Upload", "آپلود", "上传"),
        "Use numeric IP:port" to Triple("Use numeric IP:port", "آی‌پی:پورت عددی وارد کنید", "请输入数字 IP:端口"),
        "Use verified gateways first, then discover more" to Triple("Use verified gateways first, then discover more", "استفاده اولیه از درگاه‌های تاییدشده، سپس کشف موارد جدید", "优先使用已验证网关，后台继续探测新节点"),
        "Use whole numbers" to Triple("Use whole numbers", "عدد صحیح وارد کنید", "请输入整数"),
        "VPN (whole device)" to Triple("VPN (whole device)", "وی‌پی‌ان (کل دستگاه)", "全局 VPN"),
        "VPN Service" to Triple("VPN Service", "سرویس VPN", "VPN 服务"),
        "VPN connected" to Triple("VPN connected", "VPN وصل شد", "VPN 已连接"),
        "VPN interface missing" to Triple("VPN interface missing", "رابط VPN وجود ندارد", "缺少 VPN 接口"),
        "VPN mode" to Triple("VPN mode", "حالت VPN", "VPN 模式"),
        "VPN permission required" to Triple("VPN permission required", "مجوز VPN لازم است", "需要 VPN 权限"),
        "Verifying" to Triple("Verifying", "در حال اعتبارسنجی", "正在校验"),
        "Volunteer WebRTC proxies" to Triple("Volunteer WebRTC proxies", "استفاده از پروکسی‌های داوطلبانه WebRTC", "利用志愿者 WebRTC 代理穿透封锁"),
        "WARP on WARP — slowest, for the most filtered networks" to Triple("WARP on WARP — slowest, for the most filtered networks", "وارپ روی وارپ — کندترین حالت، مخصوص شدیدترین فیلترینگ‌ها", "WARP-on-WARP 双层隧道 — 速度最慢，专为极高强度审查环境设计"),
        "WARP-on-WARP" to Triple("WARP-on-WARP", "وارپ در وارپ", "WARP-on-WARP"),
        "WIREGUARD ENDPOINT DISCOVERY" to Triple("WIREGUARD ENDPOINT DISCOVERY", "شناسایی نقاط پایانی وایرگارد", "WIREGUARD 节点探测"),
        "Waiting for tunnel traffic" to Triple("Waiting for tunnel traffic", "در انتظار ترافیک تانل", "等待隧道流量"),
        "Warn" to Triple("Warn", "هشدار (Warn)", "警告 (Warn)"),
        "Warnings and errors" to Triple("Warnings and errors", "هشدارها و خطاها", "记录警告与错误"),
        "What the tunnel did" to Triple("What the tunnel did", "خلاصه عملکرد تونل", "隧道运行摘要"),
        "Which WARP tunnel carries Psiphon in Psiphon over WARP" to Triple("Which WARP tunnel carries Psiphon in Psiphon over WARP", "کدام تونل وارپ، ترافیک سایفون را در حالت «سایفون روی وارپ» حمل کند", "在“Psiphon over WARP”模式下承载赛风流量的 WARP 隧道"),
        "Which WARP tunnel carries Tor in Tor over WARP" to Triple("Which WARP tunnel carries Tor in Tor over WARP", "کدام تونل وارپ، ترافیک تور را در حالت «تور روی وارپ» حمل کند", "在“Tor over WARP”模式下承载 Tor 流量的 WARP 隧道"),
        "Will re-measure on the next connect" to Triple("Will re-measure on the next connect", "در اتصال بعدی دوباره اندازه‌گیری می‌شود", "将在下次连接时重新测量"),
        "WireGuard" to Triple("WireGuard", "وایرگارد", "WireGuard"),
        "WireGuard only. Jc/Jmin/Jmax tune junk packets; I1/I2 use Aether CPS packet patterns." to Triple("WireGuard only. Jc/Jmin/Jmax tune junk packets; I1/I2 use Aether CPS packet patterns.", "فقط مخصوص وایرگارد. متغیرهای Jc/Jmin/Jmax پکت‌های زاید را تنظیم می‌کنند؛ I1/I2 از الگوهای پکت Aether CPS استفاده می‌کنند.", "仅限 WireGuard。Jc/Jmin/Jmax 用于微调垃圾包；I1/I2 使用 Aether CPS 数据包模式。"),
        "WireGuard retries" to Triple("WireGuard retries", "تلاش مجدد وایرگارد", "WireGuard 重试"),
        "WireGuard tunnel" to Triple("WireGuard tunnel", "تونل وایرگارد", "WireGuard 原生隧道"),
        "WireGuard tunnel is active" to Triple("WireGuard tunnel is active", "تونل وایرگارد فعال است", "WireGuard 隧道已运行"),
        "WireGuard verification" to Triple("WireGuard verification", "اعتبارسنجی وایرگارد", "WireGuard 校验"),
        "WoW" to Triple("WoW", "وارپ در وارپ", "WoW"),
        "Wrap" to Triple("Wrap", "نشکن‌سازی خطوط (Wrap)", "自动换行"),
        "YOUR IP" to Triple("YOUR IP", "آی‌پی شما", "当前 IP"),
        "You're up to date" to Triple("You're up to date", "برنامه به‌روز است", "已是最新版本"),
        "Your bridge did not connect — check the line, or try Auto" to Triple("Your bridge did not connect — check the line, or try Auto", "پل شما وصل نشد — خط را بررسی کنید یا حالت خودکار را امتحان کنید", "网桥未连通 — 请检查输入内容，或改用自动"),
        "armed %s inside WARP, %s" to Triple("armed %s inside WARP, %s", "%s درون وارپ آماده‌به‌کار، %s", "%s 已在 WARP 内就绪，%s"),
        "armed Tor inside WARP, auto transport" to Triple("armed Tor inside WARP, auto transport", "تور درون وارپ آماده‌به‌کار، انتقال خودکار", "Tor 已在 WARP 内就绪，自动选择传输"),
        "auto" to Triple("auto", "خودکار", "自动"),
        "auto transport" to Triple("auto transport", "انتقال خودکار", "自动传输"),
        "dark" to Triple("dark", "تیره", "深色"),
        "direct" to Triple("direct", "مستقیم", "直连"),
        "disconnect to change" to Triple("disconnect to change", "برای تغییر قطع کنید", "需断开连接后修改"),
        "everything through the node" to Triple("everything through the node", "عبور تمام ترافیک از نود", "全部流量经节点转发"),
        "exit relay" to Triple("exit relay", "رله خروجی", "出口节点"),
        "exit relays" to Triple("exit relays", "رله خروجی", "个出口节点"),
        "for when neither exit IP is accepted" to Triple("for when neither exit IP is accepted", "برای زمانی که هیچ آی‌پی خروجی پذیرفته نمی‌شود", "两个出口 IP 均被拒绝时使用"),
        "gool" to Triple("gool", "gool", "gool"),
        "light" to Triple("light", "روشن", "浅色"),
        "local sites direct · %s" to Triple("local sites direct · %s", "سایت‌های داخلی مستقیم · %s", "国内站点直连 · %s"),
        "local sites direct, blocked sites via node" to Triple("local sites direct, blocked sites via node", "سایت‌های داخلی مستقیم، سایت‌های مسدود از طریق نود", "国内站点直连，被墙站点经节点"),
        "masque" to Triple("masque", "masque", "masque"),
        "may fall back to another country" to Triple("may fall back to another country", "ممکن است به کشور دیگری منتقل شود", "可能降级至其他国家"),
        "measuring…" to Triple("measuring…", "در حال اندازه‌گیری…", "测量中…"),
        "meek" to Triple("meek", "meek", "meek"),
        "not available with %s" to Triple("not available with %s", "با %s در دسترس نیست", "在 %s 下不可用"),
        "not available with your bridges" to Triple("not available with your bridges", "با پل‌های شما در دسترس نیست", "你的网桥不支持此模式"),
        "not tunnelled" to Triple("not tunnelled", "بدون تونل", "未走隧道"),
        "obfs4" to Triple("obfs4", "پل obfs4", "obfs4 网桥"),
        "only for the PSIPHON and TOR transports" to Triple("only for the PSIPHON and TOR transports", "فقط مخصوص پروتکل‌های سایفون و تور", "仅适用于 Psiphon 及 Tor 传输协议"),
        "only for the SHARD transport" to Triple("only for the SHARD transport", "فقط مخصوص پروتکل شارد", "仅适用于 SHARD 传输"),
        "over WARP is active" to Triple("over WARP is active", "روی وارپ فعال است", "over WARP 已运行"),
        "over WARP recovered" to Triple("over WARP recovered", "روی وارپ بازیابی شد", "over WARP 已恢复"),
        "reading from inside the tunnel" to Triple("reading from inside the tunnel", "خواندن از درون تونل", "从隧道内测得"),
        "servers in the bundled list" to Triple("servers in the bundled list", "سرور در لیست داخلی", "个内置节点"),
        "snowflake" to Triple("snowflake", "snowflake", "snowflake"),
        "tap to refresh" to Triple("tap to refresh", "برای تازه‌سازی بزنید", "点击刷新"),
        "tap to retry" to Triple("tap to retry", "برای تلاش مجدد بزنید", "点击重试"),
        "this month" to Triple("this month", "در این ماه", "本月"),
        "tuned for this network" to Triple("tuned for this network", "تنظیم‌شده برای این شبکه", "已针对此网络调优"),
        "tunnel is active" to Triple("tunnel is active", "تونل فعال است", "隧道已运行"),
        "tunnel recovered" to Triple("tunnel recovered", "تونل بازیابی شد", "隧道已恢复"),
        "tunnelled" to Triple("tunnelled", "از تونل", "已走隧道"),
        "use MSN-GUARD" to Triple("use MSN-GUARD", "از MSN-GUARD استفاده می‌کنند", "使用 MSN-GUARD"),
        "via %s" to Triple("via %s", "از طریق %s", "经 %s"),
        "wireguard" to Triple("wireguard", "wireguard", "wireguard"),
        "فارسی" to Triple("فارسی", "فارسی", "波斯语"),
        "↑ UP" to Triple("↑ UP", "↑ آپلود", "↑ 上传"),
        "↓ DOWN" to Triple("↓ DOWN", "↓ دانلود", "↓ 下载"),
    )

    /** Translate [key] into the active language, falling back to English. */
    fun t(english: String): String {
        val row = table[english]
        val l = AppLanguage.current()
        if (l == "en") return row?.first ?: english
        row ?: return english
        return when (l) {
            "fa" -> row.second.ifBlank { english }
            "zh" -> row.third.ifBlank { english }
            else -> english
        }
    }

    /**
     * Translate a %s template, then substitute [args] in order.
     *
     * A literal `%` that is not part of a `%s` placeholder is folded to a single
     * `%` — the templates are written as `%s%%` for readability (the table's keys
     * are also greppable English), and this is where the `%%` becomes one `%`.
     * Without the fold, `tf("CONNECTING %s%%", 15)` printed `15%%`.
     */
    fun tf(english: String, vararg args: Any?): String {
        var out = t(english)
        val parts = out.split("%s")
        val sb = StringBuilder()
        for ((i, p) in parts.withIndex()) {
            sb.append(p.replace("%%", "%"))
            if (i < args.size && i < parts.size - 1) sb.append(args[i].toString())
        }
        return sb.toString()
    }
}
